config/routes.rb
Smilecdn::Application.routes.draw do

  root :to => 'home#index'

  resources :vouchers
  match '/voucher/upload' => "vouchers#upload", :as => :uploadVouchers

  match '/api/redeem/:query' => "api#redeem", :constraints  => { :query => /[^\/]+/ }, :via => :post
  match '/api/mailinglist/:query' => "api#mailinglist", :constraints  => { :query => /[^\/]+/ }, :via => :post

  match '/redeem' => "redeem#index", :as => :redeem
  match '/redeem/export/:query' => "redeem#export"
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :voucher_number, :site_source, :redeemed
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  # GET /vouchers
  # GET /vouchers.json
  def index
    @vouchers = Voucher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @vouchers }
    end
  end

  # GET /vouchers/1
  # GET /vouchers/1.json
  def show
    @voucher = Voucher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @voucher }
    end
  end

  # GET /vouchers/new
  # GET /vouchers/new.json
  def new
    @voucher = Voucher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @voucher }
    end
  end

  # GET /vouchers/1/edit
  def edit
    @voucher = Voucher.find(params[:id])
  end

  # POST /vouchers
  # POST /vouchers.json
  def create
    @voucher = Voucher.new(params[:voucher])

    respond_to do |format|
      if @voucher.save
        format.html { redirect_to @voucher, :notice => 'Voucher was successfully created.' }
        format.json { render :json => @voucher, :status => :created, :location => @voucher }
      else
        format.html { render :action => "new" }
        format.json { render :json => @voucher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vouchers/1
  # PUT /vouchers/1.json
  def update
    @voucher = Voucher.find(params[:id])

    respond_to do |format|
      if @voucher.update_attributes(params[:voucher])
        format.html { redirect_to @voucher, :notice => 'Voucher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @voucher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vouchers/1
  # DELETE /vouchers/1.json
  def destroy
    @voucher = Voucher.find(params[:id])
    @voucher.destroy

    respond_to do |format|
      format.html { redirect_to vouchers_url }
      format.json { head :no_content }
    end
  end

  #Voucher Bulk Uploading
  def upload
  end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/vouchers/_form.html.erb
<%= form_for(@voucher) do |f| %>
  <% if @voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voucher.errors.count, "error") %> prohibited this voucher from being saved:</h2>

      <ul>
      <% @voucher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :voucher_number, :class => 'input-block-level', :placeholder => 'Voucher Number' %>
  <%= f.text_field :site_source, :class => 'input-block-level', :placeholder => 'Site Source' %>

  <div class="form-actions" style="margin-bottom: 0; padding-bottom: 0;">
    <%= link_to 'Back', vouchers_path, :class => 'btn' %>
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<%= pageTitle 'Smile Sciences | Edit Voucher' %>

<div class="container">
  <h1>Edit Voucher</h1>
  <div class="well">
    <% if notice %>
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= render 'form' %>
  </div>
</div>

app/views/vouchers/index.html.erb
<%= pageTitle 'Smile Sciences | Upload Voucher Numbers' %>

<div class="container">
  <h1>Voucher Numbers</h1>
  <div class="well">
    <% if notice %>
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <div class="row-fluid">
      <table class="table">
        <tr>
          <th>Voucher Number</th>
          <th>Actions</th>
        </tr>
        <% @vouchers.each do |voucher| %>
          <tr>
            <td><%= voucher.voucher_number %></td>
            <td>
              <%= link_to 'Edit', edit_voucher_path(voucher), :class => 'btn btn-info' %>
              <%= link_to 'Destroy', voucher, :class => 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </table>
      <div class="form-actions" style="margin-bottom: 0; padding-bottom: 0;">
        <%= link_to 'New Voucher', new_voucher_path, :class => 'btn' %>
        <%= link_to 'Bulk Uploader', '', :class => 'btn' %>
      </div>
    </div>
  </div>
</div>

app/views/vouchers/new.html.erb
<%= pageTitle 'Smile Sciences | New Voucher' %>

<div class="container">
  <h1>New Voucher</h1>
  <div class="well">
    <% if notice %>
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= render 'form' %>
  </div>
</div>

app/views/vouchers/show.html.erb
<div class="container">
  <h1>Voucher</h1>
  <div class="well">
    <% if notice %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= link_to 'Edit', edit_voucher_path(@voucher), :class => 'btn' %>
    <%= link_to 'Back', vouchers_path, :class => 'btn' %>
  </div>
</div>

app/views/vouchers/upload.html.erb
<%= pageTitle 'Smile Sciences | Bulk Upload Vouchers' %>

<div class="container">
  <h1>Bulk Upload Vouchers</h1>
  <div class="well">
    <% if notice %>
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>


  </div>
</div>